version: "2"
run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - goconst
    - unused
    - unparam
  settings:
    staticcheck:
      checks:
        - all
        - "-SA1019"
        - "-ST1019"
        - "-ST1000" # at least one file in a package should have a package comment
  exclusions:
    rules:
      - path-except: '(.+)_test\.go'
        linters:
          - funlen
          - goconst
          - staticcheck
